import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Container from "../components/Container";
import Hero from "../components/Hero";
import NavBar from "../components/NavBar";
import Projects from "../components/Projects";
import MusicProjects from "./MusicProjects";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>alw.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="snap-mandatory snap-y w-screen min-h-screen h-screen md:overflow-scroll">
          <section className="reltaive snap-start" id="navBar">
            <NavBar />
          </section>
          <section className="relative snap-start bg-black" id="hero">
            <Hero />
          </section>
          <section className="snap-start bg-black" id="about">
            <About />
          </section>
          <section className="snap-start bg-black" id="projects">
            <MusicProjects />
          </section>
          <section className="snap-start bg-black" id="contact">
            <Contact />
          </section>
        </div>
      </Container>
    </>
  );
};

export default Home;
